--Necessary queries
CREATE DATABASE sdslabs_kunal;

USE sdslabs_kunal;

CREATE TABLE BOOKS( BUID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50) NOT NULL, DESCRIPTION varchar(2000),TOTAL INT NOT NULL, CHECKIN INT NOT NULL,CONSTRAINT TOTALgtCHECKIN CHECK (TOTAL >= CHECKIN) );

CREATE TABLE USER( UUID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50), EMAIL VARCHAR(50) UNIQUE NOT NULL, PHN_NO BIGINT, PASSWORD VARCHAR(100), ROLE VARCHAR(10),ADMIN_REQUEST BOOLEAN DEFAULT 0 );

CREATE TABLE BORROWING_HISTORY(UUID INT, BUID INT , CHECKOUT_DATE DATE, CHECKIN_DATE DATE DEFAULT NULL, FOREIGN KEY (UUID) REFERENCES USER(UUID) );

CREATE TABLE PENDING_REQUESTS (UUID INT, BUID INT , TYPE BOOLEAN, FOREIGN KEY (UUID) REFERENCES USER(UUID), FOREIGN KEY (BUID) REFERENCES BOOKS(BUID) );

--Optional sample data entries for books table
INSERT INTO BOOKS VALUES(1,"Harry Potter 1","The first installment in the Harry Potter",1,1),(NULL,"Harry Potter 2","The second installment in the Harry Potter",2,2),(NULL,"Harry Potter 3","The third installment in the Harry Potter",5,5);
